name: Release

on:
  push:
    # Trigger when pushing tags that are versions, e.g., v0.0.1, v1.2.3
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'  # Use the Go version your project supports
        
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: 'latest-stable'
          args: release
        
      - name: Run GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: goreleaser release --rm-dist